

export const UI_PREFS_KEY = "qqfriend-launcher-ui-v2";

export const PAGE_META = Object.freeze({
  overview: ["运行中心", "总览"],
  capabilities: ["功能发现", "能力"],
  "api-center": ["模型快拆", "API 中心"],
  services: ["运行控制", "服务"],
  configuration: ["常用设置", "配置"],
  memes: ["只读归档", "旧梗库"],
  stickers: ["回复素材", "表情"],
  diagnostics: ["排查工具", "诊断"],
  summaries: ["群聊记录", "日报"],
  memory: ["按范围与用户", "记忆"],
  logs: ["运行记录", "日志"],
  maintenance: ["本地管理", "维护与外观"],
});

export const ACTION_LABELS = {
  refreshStickerCapabilities: "正在检查 NapCat 表情能力",
  cleanupStickerTemp: "正在清理表情临时文件",
  setStickerCaptureMode: "正在切换群聊采集模式",
  removeCapturedSticker: "正在移除机器人采集的表情",
  refresh: "正在刷新控制台数据",
  refreshLogs: "正在读取最新日志",
  refreshConfig: "正在读取当前配置",
  refreshMemes: "正在读取只读归档",
  refreshStickers: "正在刷新收藏表情",
  syncStickers: "正在同步 QQ 收藏表情",
  analyzeStickers: "正在分析待处理表情",
  saveStickerSettings: "正在保存表情设置",
  setStickerMode: "正在切换表情模式",
  saveSticker: "正在保存表情标签",
  simulateSticker: "正在预演表情选择",
  refreshCapabilities: "正在读取能力目录",
  refreshApiProviders: "正在读取 API 预设和插槽",
  saveApiProvider: "正在保存 API 实例",
  testApiProvider: "正在测试 API 连接",
  deleteApiProvider: "正在删除 API 实例",
  saveApiRoutes: "正在切换功能插槽",
  rollbackApiProviders: "正在回滚 API 配置",
  startAll: "正在启动全部服务",
  health: "正在检查运行状态",
  restartBridge: "正在重启 Bridge",
  stopBridge: "正在停止 Bridge",
  stopAll: "正在停止全部服务",
  diagnose: "正在模拟消息链路",
  createBackup: "正在创建安全备份",
  openLogs: "正在打开日志目录",
  saveConfig: "正在保存配置",
  setBuiltInBackground: "正在切换背景",
  setDesktopBackground: "正在读取桌面壁纸",
  chooseBackgroundImage: "正在选择背景图片",
};

export const ACTION_DONE = {
  refreshStickerCapabilities: "NapCat 表情能力已刷新",
  cleanupStickerTemp: "表情临时文件已清理",
  setStickerCaptureMode: "群聊采集模式已切换",
  removeCapturedSticker: "机器人采集表情已移除",
  refresh: "控制台数据已刷新",
  refreshLogs: "日志已刷新",
  refreshConfig: "配置已重新读取",
  refreshMemes: "只读归档已刷新",
  refreshStickers: "收藏表情已刷新",
  syncStickers: "收藏表情同步完成",
  analyzeStickers: "待处理表情分析完成",
  saveStickerSettings: "表情设置已保存",
  setStickerMode: "表情模式已切换",
  saveSticker: "表情标签已保存",
  simulateSticker: "表情预演完成",
  refreshCapabilities: "能力状态已刷新",
  refreshApiProviders: "API 状态已刷新",
  saveApiProvider: "API 实例已保存",
  testApiProvider: "API 连接测试完成",
  deleteApiProvider: "API 实例已删除",
  saveApiRoutes: "功能插槽已应用",
  rollbackApiProviders: "API 配置已回滚",
  startAll: "服务启动完成",
  health: "健康检查完成",
  restartBridge: "Bridge 已重启",
  stopBridge: "Bridge 已停止",
  stopAll: "全部服务已停止",
  diagnose: "诊断完成",
  createBackup: "备份创建完成",
  openLogs: "日志目录已打开",
  saveConfig: "配置已保存",
  setBuiltInBackground: "已使用内置背景",
  setDesktopBackground: "已使用桌面壁纸",
  chooseBackgroundImage: "背景图片已应用",
};

export const ACTION_GROUPS = {
  refreshStickerCapabilities: "stickers",
  cleanupStickerTemp: "stickers",
  setStickerCaptureMode: "stickers",
  removeCapturedSticker: "stickers",
  startAll: "runtime",
  health: "runtime",
  restartBridge: "runtime",
  stopBridge: "runtime",
  stopAll: "runtime",
  refresh: "snapshot",
  refreshStatus: "snapshot",
  refreshLogs: "logs",
  refreshConfig: "config",
  saveConfig: "config",
  refreshMemes: "memes",
  refreshStickers: "stickers",
  syncStickers: "stickers",
  analyzeStickers: "stickers",
  saveStickerSettings: "stickers",
  setStickerMode: "stickers",
  saveSticker: "stickers",
  simulateSticker: "stickers",
  refreshCapabilities: "capabilities",
  refreshApiProviders: "api-providers",
  saveApiProvider: "api-providers",
  testApiProvider: "api-providers",
  deleteApiProvider: "api-providers",
  saveApiRoutes: "api-providers",
  rollbackApiProviders: "api-providers",
};

export const STICKER_ACTIONS = [
  "refreshStickerCapabilities",
  "cleanupStickerTemp",
  "setStickerCaptureMode",
  "removeCapturedSticker",
  "syncStickers",
  "analyzeStickers",
  "saveStickerSettings",
  "setStickerMode",
  "saveSticker",
  "simulateSticker",
];

export const CONFIG_FIELDS = Object.freeze({
  cfgBotNames: "botNames",
  cfgAdminUins: "adminUins",
  cfgGroupWhitelist: "groupWhitelist",
  cfgSummaryGroups: "summaryGroupWhitelist",
  cfgResourceGroups: "resourceGroupWhitelist",
  cfgFeatureGroups: "featureGroupWhitelist",
  cfgConversationSummaryGroups: "conversationSummaryGroupWhitelist",
  cfgLongGroups: "longGroups",
  cfgFriendWhitelist: "friendWhitelist",
  cfgJmUsers: "jmUserWhitelist",
  cfgBotBlacklist: "botBlacklist",
});
