// bridge/modules/manifest.mjs - declarative module metadata for console and agents.

export const MODULE_DEFINITIONS = Object.freeze([
  {
    id: "commands",
    name: "命令系统",
    category: "core",
    enabled: true,
    entrypoints: [
      "bridge/commands/index.mjs",
      "bridge/commands/action-dispatcher.mjs",
      "bridge/admin-commands.mjs",
    ],
    commands: ["help", "ping", "status", "version", "admin help", "runtime"],
    configFields: ["botNames", "adminUins"],
    editableConfigFields: ["botNames", "adminUins"],
    healthChecks: ["command manifest loads", "registry recognizes aliases", "group actions share one mention-gated entry"],
    diagnostics: ["admin/commands", "admin/diagnose/reply"],
    tests: [
      "test/admin-commands.test.mjs",
      "test/commands-modular.test.mjs",
      "test/command-action-dispatcher.test.mjs",
    ],
    riskLevel: "medium",
    privacy: "does not expose raw private chat; command catalog is metadata only",
  },
  {
    id: "jm",
    name: "JM 下载转发",
    category: "resource",
    enabled: true,
    entrypoints: ["bridge/jm-provider.mjs", "scripts/jm_download_once.py"],
    commands: ["jm <代码>"],
    configFields: ["resourceGroupWhitelist", "jmUserWhitelist", "jmPython", "jmDomains", "jmTimeoutMs", "jmZipPassword", "jmSevenZipPath"],
    editableConfigFields: ["resourceGroupWhitelist", "jmUserWhitelist"],
    healthChecks: ["npm run check:jm", "python import jmcomic", "7z encrypted zip support"],
    diagnostics: ["admin/status.modules.jm"],
    tests: ["test/jm-provider.test.mjs"],
    riskLevel: "high",
    privacy: "downloads are temporary; no model key or user memory required",
  },
  {
    id: "group-summary",
    name: "每日群报",
    category: "content",
    enabled: true,
    entrypoints: ["bridge/group-summary/", "daily_summary.mjs", "scripts/send-summary-for-date.mjs"],
    commands: ["summary", "summary:date"],
    configFields: ["summaryGroupWhitelist"],
    editableConfigFields: ["summaryGroupWhitelist"],
    healthChecks: ["summary module import", "model-router GROUP_SUMMARY policy"],
    diagnostics: ["admin/diagnose/reply", "logs"],
    tests: ["test/group-summary.test.mjs", "test/group-summary-command.test.mjs"],
    riskLevel: "medium",
    privacy: "summaries must sanitize raw group logs and avoid sensitive details",
  },
  {
    id: "relationship",
    name: "关系与熟悉度",
    category: "memory",
    enabled: true,
    entrypoints: ["bridge/relationship.mjs", "bridge/relationship-commands.mjs", "bridge/relationship-comment.mjs"],
    commands: ["好感度", "关系", "熟悉度", "my-status"],
    configFields: [],
    editableConfigFields: [],
    healthChecks: ["relationship calculation pure functions", "comment model fallback"],
    diagnostics: ["admin/diagnose/reply"],
    tests: ["test/relationship.test.mjs", "test/relationship-commands.test.mjs", "test/relationship-comment.test.mjs"],
    riskLevel: "medium",
    privacy: "relationship means interaction familiarity, not romance; no raw chat export",
  },
  {
    id: "memory",
    name: "画像与记忆",
    category: "memory",
    enabled: true,
    entrypoints: ["bridge/memory-profile.mjs", "bridge/context-retriever.mjs", "bridge/user-preferences.mjs"],
    commands: ["我的档案", "隐私", "忘记我", "memory status", "memory summary QQ号", "memory clear user QQ号", "memory clear group"],
    configFields: ["legacyProfileRefreshEnabled"],
    editableConfigFields: [],
    healthChecks: ["memory profile load", "expiry cleanup", "privacy clear commands"],
    diagnostics: ["admin/status.modules.memory", "admin/diagnose/reply"],
    tests: ["test/memory-profile.test.mjs", "test/user-preferences.test.mjs"],
    riskLevel: "high",
    privacy: "stores summaries and preferences; raw private content must not be exposed in groups",
  },
  {
    id: "cognition",
    name: "短期认知线程",
    category: "memory",
    enabled: true,
    entrypoints: ["bridge/cognition/", "bridge/context-retriever.mjs", "bridge/context/budget.mjs"],
    commands: [],
    configFields: [],
    editableConfigFields: [],
    healthChecks: [
      "completed turn recording",
      "same-group isolation",
      "private volatile storage",
      "context hard budget",
      "thread/history message-id deduplication",
    ],
    diagnostics: ["admin/status.modules.cognition", "admin/diagnose/reply"],
    tests: ["test/cognition-thread.test.mjs", "test/context-budget.test.mjs"],
    riskLevel: "high",
    privacy: "group turns stay in the same group scope; private turns are memory-only and expire without disk persistence",
  },
  {
    id: "meme-knowledge",
    name: "梗库理解",
    category: "memory",
    enabled: true,
    entrypoints: ["bridge/knowledge/memes/", "bridge/context-retriever.mjs", "bridge/reply-group.mjs"],
    commands: ["梗库", "梗库 搜 关键词", "梗库 禁用 关键词", "梗库 启用 关键词"],
    configFields: [
      "memeLearningMode",
      "memeAutoUpdateEnabled",
      "memeUpdateIntervalMs",
      "memeUpdateLimit",
      "memeEvidenceMinSources",
      "memeEvidenceMinItems",
      "memeExpiryDays",
    ],
    editableConfigFields: [],
    healthChecks: [
      "builtin seed loads",
      "web source collection",
      "multi-source evidence verification",
      "manual field protection",
      "batch rollback",
      "context hint injection",
      "image perceptual cache",
    ],
    diagnostics: ["admin/status.modules.meme-knowledge", "admin/diagnose/reply"],
    tests: ["test/meme-knowledge.test.mjs", "test/meme-updater.test.mjs", "test/image-context.test.mjs"],
    riskLevel: "medium",
    privacy: "stores reviewed terms, public source links and aggregate usage counts; never stores group message samples, QQ ids or image files",
  },
  {
    id: "resource-transfer",
    name: "资源转发",
    category: "resource",
    enabled: true,
    entrypoints: ["bridge/resource-transfer.mjs"],
    commands: ["下载 <url>", "转发 <url>"],
    configFields: ["resourceGroupWhitelist", "resourceMaxBytes"],
    editableConfigFields: ["resourceGroupWhitelist"],
    healthChecks: ["safe URL validation", "500MB size limit", "temp cleanup"],
    diagnostics: ["admin/diagnose/reply"],
    tests: ["test/resource-transfer.test.mjs", "test/safe-url.test.mjs"],
    riskLevel: "high",
    privacy: "does not persist downloaded files after transfer workflow",
  },
  {
    id: "link-preview",
    name: "Link Preview",
    category: "content",
    enabled: true,
    entrypoints: ["bridge/services/link-preview/", "bridge/reply-handlers.mjs"],
    commands: ["auto link preview", "preview <url>"],
    configFields: ["linkPreviewEnabled"],
    editableConfigFields: [],
    healthChecks: ["safe URL validation", "redirect protection", "generic page metadata parsing", "GitHub repository metadata fallback"],
    diagnostics: ["admin/status.modules.linkPreview", "admin/diagnose/reply"],
    tests: ["test/core.test.mjs", "test/github-preview.test.mjs", "test/link-preview-policy.test.mjs", "test/safe-url.test.mjs"],
    riskLevel: "medium",
    privacy: "fetches public link metadata only; private and local network URLs are blocked",
  },
  {
    id: "wordcloud",
    name: "群词云",
    category: "content",
    enabled: true,
    entrypoints: ["bridge/features/index.mjs", "bridge/features/wordcloud/"],
    commands: ["词云", "今日词云", "昨日词云", "词云 7天", "wordcloud"],
    configFields: ["featureGroupWhitelist", "wordcloudMaxMessages"],
    editableConfigFields: ["featureGroupWhitelist"],
    healthChecks: ["feature command entrypoint", "word frequency aggregation", "image fallback"],
    diagnostics: ["admin/status.modules.wordcloud", "admin/diagnose/reply"],
    tests: ["test/wordcloud.test.mjs"],
    riskLevel: "medium",
    privacy: "uses group chat history only for aggregated terms; no raw chat export",
  },
  {
    id: "api-providers",
    name: "API 快拆与模型路由",
    category: "core",
    enabled: true,
    entrypoints: ["bridge/api-providers/", "bridge/model-router.mjs", "bridge/admin-api/api-provider-manager.mjs"],
    commands: ["缓存命中", "cache stats"],
    configFields: ["apiProviders", "apiTaskRoutes", "apiTaskReasoning"],
    editableConfigFields: ["apiProviders", "apiTaskRoutes", "apiTaskReasoning"],
    healthChecks: [
      "provider adapter normalization",
      "task reasoning policy",
      "secret sidecar isolation",
      "runtime cache invalidation",
      "fallback route protection",
      "pseudonymous prompt-cache usage accounting",
    ],
    diagnostics: ["admin/api-providers", "provider connection test"],
    tests: ["test/api-providers.test.mjs", "test/api-usage.test.mjs", "test/reasoning-policy.test.mjs", "test/model-router.test.mjs"],
    riskLevel: "high",
    privacy: "API credentials stay in local sidecars; cache metrics keep only numeric usage and salted user identifiers",
  },
  {
    id: "stickers",
    name: "收藏表情回复",
    category: "content",
    enabled: true,
    entrypoints: ["bridge/features/stickers/", "bridge/admin-api/sticker-manager.mjs"],
    commands: [],
    configFields: ["stickerEnabled", "stickerGroupWhitelist", "stickerMode", "stickerCaptureMode"],
    editableConfigFields: ["stickerGroupWhitelist", "stickerMode", "stickerCaptureMode"],
    healthChecks: ["NapCat 4.18.13 云收藏", "QQ 临时图片续签", "群聊采集队列", "图片指纹去重", "语义候选选择", "文字回复失败隔离"],
    diagnostics: ["admin/status.modules.stickers", "admin/stickers", "admin/stickers/image"],
    tests: ["test/stickers.test.mjs", "test/admin-api.test.mjs", "test/launcher-frontend.test.mjs"],
    riskLevel: "medium",
    privacy: "不保存表情图片；发送者只保存带随机盐的不可逆摘要；上传临时文件立即删除；发送密钥不向控制台暴露",
  },
  {
    id: "output-safety",
    name: "输出安全",
    category: "safety",
    enabled: true,
    entrypoints: ["bridge/thinking.mjs", "bridge/output-pipeline.mjs", "bridge/outbound-message.mjs"],
    commands: [],
    configFields: [],
    editableConfigFields: [],
    healthChecks: ["private reasoning fields blocked", "final-content-only output", "long text splitting", "secret leak filter"],
    diagnostics: ["admin/diagnose/reply"],
    tests: ["test/output-pipeline.test.mjs", "test/outbound-message.test.mjs", "test/model-output.test.mjs"],
    riskLevel: "high",
    privacy: "blocks chain-of-thought, reasoning_content, analysis, thinking and obvious credential leaks",
  },
]);

export function moduleIds() {
  return MODULE_DEFINITIONS.map(module => module.id);
}
