import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

export function parseScaffoldArgs(argv = []) {
  const options = {
    id: "",
    permission: "user",
    aliases: [],
    helpLine: "",
    write: false,
  };

  for (const arg of argv) {
    if (arg === "--write") {
      options.write = true;
      continue;
    }
    if (arg.startsWith("--permission=")) {
      options.permission = arg.slice("--permission=".length);
      continue;
    }
    if (arg.startsWith("--aliases=")) {
      options.aliases = splitCsv(arg.slice("--aliases=".length));
      continue;
    }
    if (arg.startsWith("--help=")) {
      options.helpLine = arg.slice("--help=".length);
      continue;
    }
    if (!arg.startsWith("--") && !options.id) {
      options.id = arg;
      continue;
    }
    throw new Error("unknown argument: " + arg);
  }

  return normalizeScaffoldOptions(options);
}

export function normalizeScaffoldOptions(options = {}) {
  const id = normalizeCommandId(options.id);
  const permission = options.permission || "user";
  if (permission !== "user" && permission !== "admin") {
    throw new Error("permission must be user or admin");
  }
  return {
    root: options.root || ROOT,
    id,
    permission,
    aliases: Array.isArray(options.aliases) ? options.aliases.filter(Boolean) : [],
    helpLine: String(options.helpLine || "").trim(),
    write: options.write === true,
  };
}

export function normalizeCommandId(value) {
  const id = String(value || "").trim().toLowerCase();
  if (!/^[a-z][a-z0-9-]{1,48}$/.test(id)) {
    throw new Error("command id must be kebab-case, start with a letter, and be 2-49 chars");
  }
  return id;
}

export function scaffoldCommand(options = {}) {
  const normalized = normalizeScaffoldOptions(options);
  const files = buildScaffoldFiles(normalized);
  const result = {
    id: normalized.id,
    permission: normalized.permission,
    write: normalized.write,
    manifestSnippet: buildManifestSnippet(normalized),
    files: files.map(item => item.path),
  };

  if (!normalized.write) return result;
  for (const file of files) writeNewFile(normalized.root, file.path, file.content);
  return result;
}

export function buildManifestSnippet(options = {}) {
  const normalized = normalizeScaffoldOptions(options);
  const lines = [
    "  {",
    '    id: "' + normalized.id + '",',
    '    permission: "' + normalized.permission + '",',
    "    aliases: " + JSON.stringify(normalized.aliases) + ",",
  ];
  if (normalized.permission === "admin") {
    lines.push('    adminSection: "base",');
  } else {
    lines.push("    helpPage: 2,");
  }
  if (normalized.helpLine) {
    lines.push("    helpLine: " + JSON.stringify(normalized.helpLine) + ",");
  }
  lines.push("  },");
  return lines.join("\n");
}

export function buildScaffoldFiles(options = {}) {
  const normalized = normalizeScaffoldOptions(options);
  const baseName = normalized.id;
  return [
    {
      path: "bridge/commands/modules/" + baseName + ".mjs",
      content: buildCommandModuleSource(normalized),
    },
    {
      path: "test/" + baseName + "-command.test.mjs",
      content: buildCommandTestSource(normalized),
    },
  ];
}

export function buildCommandModuleSource(options = {}) {
  const normalized = normalizeScaffoldOptions(options);
  const fn = "build" + toPascalCase(normalized.id) + "CommandReply";
  const firstAlias = normalized.aliases[0] || normalized.id;
  return [
    "// Generated by scripts/scaffold-command.mjs.",
    "const COMMAND_ALIASES = new Set(" + JSON.stringify([firstAlias, ...normalized.aliases.filter(alias => alias !== firstAlias)]) + ");",
    "",
    "export function " + fn + "(cmd, options = {}) {",
    "  void options;",
    "  if (!COMMAND_ALIASES.has(cmd)) return null;",
    '  return "' + normalized.id + ' command is scaffolded but not implemented yet."; ',
    "}",
    "",
  ].join("\n");
}

export function buildCommandTestSource(options = {}) {
  const normalized = normalizeScaffoldOptions(options);
  const fn = "build" + toPascalCase(normalized.id) + "CommandReply";
  const firstAlias = normalized.aliases[0] || normalized.id;
  return [
    'import assert from "node:assert/strict";',
    'import { describe, it } from "node:test";',
    "",
    'import { ' + fn + ' } from "../bridge/commands/modules/' + normalized.id + '.mjs";',
    "",
    'describe("' + normalized.id + ' command scaffold", () => {',
    '  it("returns a reserved scaffold reply for known aliases", () => {',
    '    assert.match(' + fn + "(" + JSON.stringify(firstAlias) + '), /scaffolded but not implemented/);',
    '    assert.equal(' + fn + '("unknown"), null);',
    "  });",
    "});",
    "",
  ].join("\n");
}

function writeNewFile(root, relativePath, content) {
  const absolute = path.resolve(root, relativePath);
  const normalizedRoot = path.resolve(root);
  if (!absolute.startsWith(normalizedRoot + path.sep)) {
    throw new Error("refusing to write outside root: " + relativePath);
  }
  if (fs.existsSync(absolute)) throw new Error("file already exists: " + relativePath);
  fs.mkdirSync(path.dirname(absolute), { recursive: true });
  fs.writeFileSync(absolute, content, "utf8");
}

function splitCsv(value) {
  return String(value || "")
    .split(",")
    .map(item => item.trim())
    .filter(Boolean);
}

function toPascalCase(value) {
  return String(value)
    .split("-")
    .filter(Boolean)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function printResult(result) {
  console.log("Command scaffold: " + result.id);
  console.log("Mode: " + (result.write ? "write" : "dry-run"));
  console.log("Files:");
  for (const file of result.files) console.log("  " + file);
  console.log("");
  console.log("Manifest snippet:");
  console.log(result.manifestSnippet);
  if (!result.write) {
    console.log("");
    console.log("Run with --write to create files. Add the manifest snippet and wire the module into dispatcher manually.");
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    printResult(scaffoldCommand(parseScaffoldArgs(process.argv.slice(2))));
  } catch (error) {
    console.error("[scaffold-command] " + error.message);
    process.exitCode = 1;
  }
}
